name: README Spam Detection

on:
  pull_request:
    paths:
      - '**/README*'
      - '**/readme*'
      - '**/Readme*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  detect-spam:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check for spam in README changes
        id: spam-check
        uses: rbadillap/ai-readme-antispam@v1
        with:
          api-key: ${{ secrets.AI_GATEWAY_API_KEY }}
          model: 'openai/gpt-4o'
          
      - name: Output spam detection results
        run: |
          echo "Spam Detection Results:"
          echo "Type: ${{ steps.spam-check.outputs.spam-type }}"
          echo "Reason: ${{ steps.spam-check.outputs.analysis-reason }}"
          echo ""
          echo "Full JSON:"
          cat << 'EOF'
          ${{ steps.spam-check.outputs.raw-json }}
          EOF
                
      - name: Close PR if spam detected
        if: steps.spam-check.outputs.spam-type == 'spam'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "This PR may have been opened accidentally or contains changes that don't align with our documentation guidelines. I'm closing it now, but feel free to open a new PR with more substantial documentation improvements!\n\n" +
                    "Reason: ${{ steps.spam-check.outputs.analysis-reason }}"
            })
            
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              state: 'closed'
            })
