name: README Spam Detection

on:
  pull_request:
    paths:
      - 'README.md'

jobs:
  detect-spam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get diff between PR and destination branch
        id: get-diff
        run: |
          # Get the base branch (destination branch)
          BASE_REF="${{ github.event.pull_request.base.ref }}"
          
          # Get the diff for README.md
          git fetch origin $BASE_REF
          DIFF=$(git diff origin/$BASE_REF...HEAD -- README.md)
          
          # Output the diff for the next step
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Analyze README changes for spam
        id: analyze-readme
        uses: vercel/ai-action@v2
        with:
          prompt: |
            Some PRs modify only the README with trivial, irrelevant, or promotional link changes. These are considered spam unless:
              • They fix a real typographical error,
              • They add useful documentation related to the project,
              • Or they include verifiable technical examples.
            
            Your task is to categorize the changes into one of these categories:
            - "spam": The changes contain spam content
            - "unknown": You're not sure if it's spam or not
            - "none": The changes are legitimate and not spam
            
            Here is the git diff:
            
            ${{ steps.get-diff.outputs.diff }}
          schema: |
            {
              "$schema": "https://json-schema.org/draft/2020-12/schema",
              "type": "object",
              "properties": {
                "analysis": {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string",
                      "enum": ["spam", "unknown", "none"]
                    },
                    "reason": {
                      "type": "string"
                    }
                  },
                  "required": ["type"],
                  "additionalProperties": false
                }
              },
              "required": ["analysis"],
              "additionalProperties": false
            }
          model: 'openai/gpt-4o'
          api-key: ${{ secrets.AI_GATEWAY_API_KEY }}
          
      - name: Output spam detection results
        run: |
          echo "Spam Detection Results:"
          echo '${{ steps.analyze-readme.outputs.json }}'
          
          # Parse and display specific fields
          echo "Type: ${{ fromJson(steps.analyze-readme.outputs.json).analysis.type }}"
          echo "Reason: ${{ fromJson(steps.analyze-readme.outputs.json).analysis.reason }}"
